version: "3.7"

services:
  database:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: bjason01/vet-api:develop
    hostname: app
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    env_file: .env
    ports:
      - "8000:8000"

    volumes:
      - ".:/app"
      - "home:/home/app"
      - bundle_path:/usr/local/bundle

    links:
      - "database:database"

volumes:
  home:
  pgdata:
  bundle_path:
